# -*- coding: utf-8 -*-
"""Regresao_imoveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBEwtoWHgGf0pDAufXkx0Amt2J9vHHXC
"""

# Célula 1: Preparando o terreno

import pandas as pd
from sklearn.linear_model import LinearRegression

# Criando os nossos dados historicos (o passado para ensinar a maquina)

dados = {
    'tamanho_m2': [50,70,80,100,120],
    'Preco': [150000,210000,240000,300000,360000]
}

df = pd.DataFrame(dados)
print("Os nossos dados de treino: ")
display(df)

# Célula 2: Gerar um grafico de disperção(Scatter Plot)
df.plot(kind='scatter',x='tamanho_m2',y='Preco',color='blue',title='Relação: Tamanho vs Preco')

# Célula 3: Separando x e y
X = df[['tamanho_m2']]
y = df['Preco']

# Célula 4: Criando e Treinando IA
modelo_ia = LinearRegression() # Criando o "celebro" vazio

# Vamos treinar a IA passando os Tamanhos (x) e os Precos(y)

modelo_ia.fit(X,y)

print("A inteligencia artificial foi treinada com sucesso!")

# Célula 5: A hora da verdade (Pedição)

# Vamos criar uma mini-tabela com1 linha par a nova casa, com o mesmo nome da coluna
tamanho_nova_casa = pd.DataFrame({'tamanho_m2': [90]}) # Queremos saber o preço de uma casa com 90m2

# Utilizando o método .predict() para a maquina predizer o preço
preco_estimado = modelo_ia.predict(tamanho_nova_casa)

print(f"A IA avalivou a casa em R$: {preco_estimado[0]:.2f}")